# Codes for the creating database

Import all modules

In [1]:
pip install -U googlemaps

Requirement already satisfied: googlemaps in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (4.10.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (from googlemaps) (2.27.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/kannuoya/opt/anaconda3/lib/python3.9/site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.26.9)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import json
import requests
import re
import pandas as pd
from bs4 import BeautifulSoup # library for web scrapping 
import googlemaps #api

# 1. Get All Boroughs' Coordinates (include City of London) - Web Scrapper
Website address: https://en.wikipedia.org/wiki/List_of_London_boroughs

In [3]:
# get coordinates of every Boroughs in London (32 of them) and City of London --> total 33
# getting data from internet, URL of the Wikipedia page containing the list of London boroughs
wiki_url = 'https://en.wikipedia.org/wiki/List_of_London_boroughs'
raw_wiki_page= requests.get(wiki_url, timeout = 2).text

soup = BeautifulSoup(raw_wiki_page, 'html.parser')

# Find the table containing the list of boroughs
table = soup.find_all('table', {'class': 'wikitable sortable'})[0]

# Create a DataFrame from the table
full_boroughs_table = pd.read_html(str(table), index_col=None, header=0)[0]
full_boroughs_table

,Borough,Inner,Status,Local authority,Political control,Headquarters,Area (sq mi),Population(2019 est),Co-ordinates,Nr. inmap
0,Barking and Dagenham[note 1],NaN,NaN,Barking and Dagenham London Borough Council,Labour,"Town Hall, 1 Town Square",13.93,212906,".mw-parser-output .geo-default,.mw-parser-outp...",25
1,Barnet,NaN,NaN,Barnet London Borough Council,Labour,"Barnet House, 2 Bristol Avenue, Colindale",33.49,395896,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W,31
2,Bexley,NaN,NaN,Bexley London Borough Council,Conservative,"Civic Offices, 2 Watling Street",23.38,248287,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E,23
3,Brent,NaN,NaN,Brent London Borough Council,Labour,"Brent Civic Centre, Engineers Way",16.70,329771,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W,12
4,Bromley,NaN,NaN,Bromley London Borough Council,Conservative,"Civic Centre, Stockwell Close",57.97,332336,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E,20
5,Camden,NaN,NaN,Camden London Borough Council,Labour,5 Pancras Square,8.40,270029,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W,11
6,Croydon,NaN,NaN,Croydon London Borough Council,Conservative (council NOC),"Bernard Weatherill House, Mint Walk",33.41,386710,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W,19
7,Ealing,NaN,NaN,Ealing London Borough Council,Labour,"Perceval House, 14-16 Uxbridge Road",21.44,341806,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W,13
8,Enfield,NaN,NaN,Enfield London Borough Council,Labour,"Civic Centre, Silver Street",31.74,333794,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W,30
9,Greenwich[note 2],[note 3],Royal,Greenwich London Borough Council,Labour,"Woolwich Town Hall, Wellington Street",18.28,287942,51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E,22
10,Hackney,NaN,NaN,Hackney London Borough Council,Labour,"Hackney Town Hall, Mare Street",7.36,281120,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W,9
11,Hammersmith and Fulham[note 4],NaN,NaN,Hammersmith and Fulham London Borough Council,Labour,"Town Hall, King Street",6.33,185143,51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W,4
12,Haringey,[note 3],NaN,Haringey London Borough Council,Labour,"Civic Centre, High Road",11.42,268647,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W,29
13,Harrow,NaN,NaN,Harrow London Borough Council,Labour,"Civic Centre, Station Road",19.49,251160,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W,32
14,Havering,NaN,NaN,Havering London Borough Council,Conservative (council NOC),"Town Hall, Main Road",43.35,259552,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E,24
15,Hillingdon,NaN,NaN,Hillingdon London Borough Council,Conservative,"Civic Centre, High Street",44.67,306870,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W,33
16,Hounslow,NaN,NaN,Hounslow London Borough Council,Labour,"Hounslow House, 7 Bath Road",21.61,271523,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W,14
17,Islington,NaN,NaN,Islington London Borough Council,Labour,"Customer Centre, 222 Upper Street",5.74,242467,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W,10
18,Kensington and Chelsea,NaN,Royal,Kensington and Chelsea London Borough Council,Conservative,"The Town Hall, Hornton Street",4.68,156129,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W,3
19,Kingston upon Thames,NaN,Royal,Kingston upon Thames London Borough Council,Liberal Democrat,"Guildhall, High Street",14.38,177507,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W,16
20,Lambeth,NaN,NaN,Lambeth London Borough Council,Labour,"Lambeth Town Hall, Brixton Hill",10.36,326034,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W,6
21,Lewisham,NaN,NaN,Lewisham London Borough Council,Labour,"Town Hall, 1 Catford Road",13.57,305842,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W,21
22,Merton,NaN,NaN,Merton London Borough Council,Labour,"Civic Centre, London Road",14.52,206548,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W,17
23,Newham,[note 3],NaN,Newham London Borough Council,Labour,"Newham Dockside, 1000 Dockside Road",13.98,353134,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E,27
24,Redbridge,NaN,NaN,Redbridge London Borough Council,Labour,"Town Hall, 128-142 High Road",21.78,305222,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E,26
25,Richmond upon Thames,NaN,NaN,Richmond upon Thames London Borough Council,Liberal Democrat,"Civic Centre, 44 York Street",22.17,198019,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W,15
26,Southwark,NaN,NaN,Southwark London Borough Council,Labour,160 Tooley Street,11.14,318830,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W,7
27,Sutton,NaN,NaN,Sutton London Borough Council,Liberal Democrat,"Civic Offices, St Nicholas Way",16.93,206349,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W,18
28,Tower Hamlets,NaN,NaN,Tower Hamlets London Borough Council,Labour,"Town Hall, Whitechapel Road",7.63,324745,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W,8
29,Waltham Forest,NaN,NaN,Waltham Forest London Borough Council,Labour,"Waltham Forest Town Hall, Forest Road",14.99,276983,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W,28
30,Wandsworth,NaN,NaN,Wandsworth London Borough Council,Labour,"The Town Hall, Wandsworth High Street",13.23,329677,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W,5
31,Westminster,NaN,City,Westminster City Council,Labour,"Westminster City Hall, 64 Victoria Street",8.29,261317,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W,2

## Keep only the required columns for Borough names and their Co-ordinates

In [4]:
required_borough_table = full_boroughs_table[['Borough','Co-ordinates']]
required_borough_table

,Borough,Co-ordinates
0,Barking and Dagenham[note 1],".mw-parser-output .geo-default,.mw-parser-outp..."
1,Barnet,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
2,Bexley,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
3,Brent,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
4,Bromley,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
5,Camden,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
6,Croydon,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
7,Ealing,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
8,Enfield,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
9,Greenwich[note 2],51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
10,Hackney,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
11,Hammersmith and Fulham[note 4],51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
12,Haringey,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
13,Harrow,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
14,Havering,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
15,Hillingdon,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
16,Hounslow,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
17,Islington,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
18,Kensington and Chelsea,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
19,Kingston upon Thames,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
20,Lambeth,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
21,Lewisham,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
22,Merton,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
23,Newham,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
24,Redbridge,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
25,Richmond upon Thames,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
26,Southwark,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
27,Sutton,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
28,Tower Hamlets,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
29,Waltham Forest,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
30,Wandsworth,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
31,Westminster,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

## Clean the data

In [5]:
# Borough column
# Iterate over the 'Borough' column and clean each entry
cleaned_boroughs = []
for borough in required_borough_table['Borough']:
    cleaned_name = borough.split('[')[0].strip()
    cleaned_boroughs.append(cleaned_name)

# Updating existing 'Borough' column
required_borough_table['Borough'] = cleaned_boroughs
required_borough_table

/var/folders/l6/dfw3zk0s5tbdf21c6512l8k00000gn/T/ipykernel_1722/3684356183.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  required_borough_table['Borough'] = cleaned_boroughs

                   Borough                                       Co-ordinates
0     Barking and Dagenham  .mw-parser-output .geo-default,.mw-parser-outp...
1                   Barnet        51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
2                   Bexley        51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
3                    Brent        51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
4                  Bromley        51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
5                   Camden        51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
6                  Croydon        51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
7                   Ealing        51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
8                  Enfield        51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
9                Greenwich        51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
10                 Hackney        51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
11  Hammersmith and Fulham        51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
12                Haringey        51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
13                  Harrow        51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
14                Havering        51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
15              Hillingdon        51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
16                Hounslow        51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
17               Islington        51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
18  Kensington and Chelsea        51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
19    Kingston upon Thames        51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
20                 Lambeth        51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
21                Lewisham        51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
22                  Merton        51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
23                  Newham        51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
24               Redbridge        51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
25    Richmond upon Thames        51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
26               Southwark        51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
27                  Sutton        51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
28           Tower Hamlets        51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
29          Waltham Forest        51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
30              Wandsworth        51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
31             Westminster        51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

In [6]:
# Covert Co-ordinates from degree form to float form
original_string = required_borough_table['Co-ordinates'][0]
pattern = r'\d{2}°\d{2}′\d{2}″N \d{1,2}°\d{2}′\d{2}″E.*?\d{2}\.\d+°N \d{1,3}\.\d+°E'

# Search for the pattern in the original string
match = re.search(pattern, original_string)

# Extract the matched part
result = match.group() if match else 'No match found'

required_borough_table['Co-ordinates'][0] = result
required_borough_table

/var/folders/l6/dfw3zk0s5tbdf21c6512l8k00000gn/T/ipykernel_1722/950254437.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  required_borough_table['Co-ordinates'][0] = result

                   Borough                                 Co-ordinates
0     Barking and Dagenham  51°33′39″N 0°09′21″E﻿ / ﻿51.5607°N 0.1557°E
1                   Barnet  51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
2                   Bexley  51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
3                    Brent  51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
4                  Bromley  51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
5                   Camden  51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
6                  Croydon  51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
7                   Ealing  51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
8                  Enfield  51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
9                Greenwich  51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
10                 Hackney  51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
11  Hammersmith and Fulham  51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
12                Haringey  51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
13                  Harrow  51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
14                Havering  51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
15              Hillingdon  51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
16                Hounslow  51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
17               Islington  51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
18  Kensington and Chelsea  51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
19    Kingston upon Thames  51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
20                 Lambeth  51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
21                Lewisham  51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
22                  Merton  51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
23                  Newham  51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
24               Redbridge  51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
25    Richmond upon Thames  51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
26               Southwark  51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
27                  Sutton  51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
28           Tower Hamlets  51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
29          Waltham Forest  51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
30              Wandsworth  51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
31             Westminster  51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W

## Add data of City of London

In [7]:
new_data = {
    'Borough': 'City of London',
    'Co-ordinates': '51°30′28″N 0°05′43″W / 51.5077°N 0.0953°W'}
required_borough_table_with_col = required_borough_table.append(new_data, ignore_index=True)
required_borough_table_with_col

/var/folders/l6/dfw3zk0s5tbdf21c6512l8k00000gn/T/ipykernel_1722/4213725435.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  required_borough_table_with_col = required_borough_table.append(new_data, ignore_index=True)

                   Borough                                 Co-ordinates
0     Barking and Dagenham  51°33′39″N 0°09′21″E﻿ / ﻿51.5607°N 0.1557°E
1                   Barnet  51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W
2                   Bexley  51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E
3                    Brent  51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W
4                  Bromley  51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E
5                   Camden  51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W
6                  Croydon  51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W
7                   Ealing  51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W
8                  Enfield  51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W
9                Greenwich  51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E
10                 Hackney  51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W
11  Hammersmith and Fulham  51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W
12                Haringey  51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W
13                  Harrow  51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W
14                Havering  51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E
15              Hillingdon  51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W
16                Hounslow  51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W
17               Islington  51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W
18  Kensington and Chelsea  51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W
19    Kingston upon Thames  51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W
20                 Lambeth  51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W
21                Lewisham  51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W
22                  Merton  51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W
23                  Newham  51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E
24               Redbridge  51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E
25    Richmond upon Thames  51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W
26               Southwark  51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W
27                  Sutton  51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W
28           Tower Hamlets  51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W
29          Waltham Forest  51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W
30              Wandsworth  51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W
31             Westminster  51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W
32          City of London    51°30′28″N 0°05′43″W / 51.5077°N 0.0953°W

## Converting the Co-ordinates in degree form to float form
We only keep the second Decimal Format and convert to plus minus form (i.e., replacing 'N' and 'E' with positive values and 'S' and 'W' with negative values) as this is what api using

In [8]:
def convert_to_decimal(coord):
    """
    This function is to convert DSM into convert coordinate string to decimal with plus-minus form
    
    coord: string
    return: string in longtitude and latitude format
    """
    match = re.search(r'(\d+\.\d+)°([NS])\s+(\d+\.\d+)°([EW])', coord)
    if match:
        lat, lat_hemi, lon, lon_hemi = match.groups()
        lat = float(lat) * (-1 if lat_hemi == 'S' else 1)
        lon = float(lon) * (-1 if lon_hemi == 'W' else 1)
        return f"{lat}, {lon}"
    return 'No match found'


required_borough_table_with_col['Converted_Coordinates'] = required_borough_table_with_col['Co-ordinates'].apply(lambda x: convert_to_decimal(x))
required_borough_table_with_col

,Borough,Co-ordinates,Converted_Coordinates
0,Barking and Dagenham,51°33′39″N 0°09′21″E﻿ / ﻿51.5607°N 0.1557°E,"51.5607, 0.1557"
1,Barnet,51°37′31″N 0°09′06″W﻿ / ﻿51.6252°N 0.1517°W,"51.6252, -0.1517"
2,Bexley,51°27′18″N 0°09′02″E﻿ / ﻿51.4549°N 0.1505°E,"51.4549, 0.1505"
3,Brent,51°33′32″N 0°16′54″W﻿ / ﻿51.5588°N 0.2817°W,"51.5588, -0.2817"
4,Bromley,51°24′14″N 0°01′11″E﻿ / ﻿51.4039°N 0.0198°E,"51.4039, 0.0198"
5,Camden,51°31′44″N 0°07′32″W﻿ / ﻿51.5290°N 0.1255°W,"51.529, -0.1255"
6,Croydon,51°22′17″N 0°05′52″W﻿ / ﻿51.3714°N 0.0977°W,"51.3714, -0.0977"
7,Ealing,51°30′47″N 0°18′32″W﻿ / ﻿51.5130°N 0.3089°W,"51.513, -0.3089"
8,Enfield,51°39′14″N 0°04′48″W﻿ / ﻿51.6538°N 0.0799°W,"51.6538, -0.0799"
9,Greenwich,51°29′21″N 0°03′53″E﻿ / ﻿51.4892°N 0.0648°E,"51.4892, 0.0648"
10,Hackney,51°32′42″N 0°03′19″W﻿ / ﻿51.5450°N 0.0553°W,"51.545, -0.0553"
11,Hammersmith and Fulham,51°29′34″N 0°14′02″W﻿ / ﻿51.4927°N 0.2339°W,"51.4927, -0.2339"
12,Haringey,51°36′00″N 0°06′43″W﻿ / ﻿51.6000°N 0.1119°W,"51.6, -0.1119"
13,Harrow,51°35′23″N 0°20′05″W﻿ / ﻿51.5898°N 0.3346°W,"51.5898, -0.3346"
14,Havering,51°34′52″N 0°11′01″E﻿ / ﻿51.5812°N 0.1837°E,"51.5812, 0.1837"
15,Hillingdon,51°32′39″N 0°28′34″W﻿ / ﻿51.5441°N 0.4760°W,"51.5441, -0.476"
16,Hounslow,51°28′29″N 0°22′05″W﻿ / ﻿51.4746°N 0.3680°W,"51.4746, -0.368"
17,Islington,51°32′30″N 0°06′08″W﻿ / ﻿51.5416°N 0.1022°W,"51.5416, -0.1022"
18,Kensington and Chelsea,51°30′07″N 0°11′41″W﻿ / ﻿51.5020°N 0.1947°W,"51.502, -0.1947"
19,Kingston upon Thames,51°24′31″N 0°18′23″W﻿ / ﻿51.4085°N 0.3064°W,"51.4085, -0.3064"
20,Lambeth,51°27′39″N 0°06′59″W﻿ / ﻿51.4607°N 0.1163°W,"51.4607, -0.1163"
21,Lewisham,51°26′43″N 0°01′15″W﻿ / ﻿51.4452°N 0.0209°W,"51.4452, -0.0209"
22,Merton,51°24′05″N 0°11′45″W﻿ / ﻿51.4014°N 0.1958°W,"51.4014, -0.1958"
23,Newham,51°30′28″N 0°02′49″E﻿ / ﻿51.5077°N 0.0469°E,"51.5077, 0.0469"
24,Redbridge,51°33′32″N 0°04′27″E﻿ / ﻿51.5590°N 0.0741°E,"51.559, 0.0741"
25,Richmond upon Thames,51°26′52″N 0°19′34″W﻿ / ﻿51.4479°N 0.3260°W,"51.4479, -0.326"
26,Southwark,51°30′13″N 0°04′49″W﻿ / ﻿51.5035°N 0.0804°W,"51.5035, -0.0804"
27,Sutton,51°21′42″N 0°11′40″W﻿ / ﻿51.3618°N 0.1945°W,"51.3618, -0.1945"
28,Tower Hamlets,51°30′36″N 0°00′21″W﻿ / ﻿51.5099°N 0.0059°W,"51.5099, -0.0059"
29,Waltham Forest,51°35′27″N 0°00′48″W﻿ / ﻿51.5908°N 0.0134°W,"51.5908, -0.0134"
30,Wandsworth,51°27′24″N 0°11′28″W﻿ / ﻿51.4567°N 0.1910°W,"51.4567, -0.191"
31,Westminster,51°29′50″N 0°08′14″W﻿ / ﻿51.4973°N 0.1372°W,"51.4973, -0.1372"
32,City of London,51°30′28″N 0°05′43″W / 51.5077°N 0.0953°W,"51.5077, -0.0953"

# 2. Google Maps API

Documentation link: https://developers.google.com/maps/documentation/places/web-service 

Read the key:

In [9]:
with open('keys.json') as f:
    keys = json.load(f)
api_key = keys['googleapi']['api_key']

In [10]:
# initialize the Google Maps client
gmaps = googlemaps.Client(key=api_key)


def get_cafe_details(borough_coordinates):
    """
    This function is to fetch location details using coordinates of each borough center
    borough_coordinates: coordinates of the borough center
    Return: dataframe of required data
    """
    
    cafe = []
    
    places = gmaps.places_nearby(
    location=borough_coordinates,
    radius=5000,  # Search radius in meters (adjust as needed)
    type="cafe")
        
    for place in places['results']:
        cafe_data = {
            'Cafe_Name': place['name'],
            'Cafe_Coordinates': place['geometry'],
            'Place_Id': place['place_id'],
            'Cafe_Types': place['types'],
            'Rating': place.get('rating'),
            'Number_Ratings': place.get('user_ratings_total'),
            'Vicinity': place.get('vicinity')
        }
        cafe.append(cafe_data)
    
    return pd.DataFrame(cafe)

## Get cafe's information

In [11]:
cafe_details = []

for coord in required_borough_table_with_col['Converted_Coordinates']:
    other = get_cafe_details(coord)
    cafe_details.append(other)
cafe_details = pd.concat(cafe_details, ignore_index=True)
cafe_details

,Cafe_Name,Cafe_Coordinates,Place_Id,Cafe_Types,Rating,Number_Ratings,Vicinity
0,Take a Break,"{'location': {'lat': 51.55102600000001, 'lng':...",ChIJP5iSZRul2EcRuLlMBSZy-JY,"[cafe, point_of_interest, food, establishment]",4.0,40.0,"244 Oxlow Lane, Dagenham"
1,Asda Dagenham Superstore,"{'location': {'lat': 51.5301912, 'lng': 0.1422...",ChIJdwGW-HOl2EcRkRKhL91oI_s,"[supermarket, atm, pharmacy, cafe, gas_station...",3.6,822.0,"Merrielands Crescent, Dagenham"
2,Becontree Heath Leisure Centre,"{'location': {'lat': 51.5609465, 'lng': 0.1488...",ChIJfRvpP_yk2EcRMHJ8P6PE448,"[gym, cafe, health, school, point_of_interest,...",3.6,824.0,"Althorne Way, Dagenham"
3,Harrow Lodge Leisure Centre,"{'location': {'lat': 51.5613365, 'lng': 0.2070...",ChIJbz00eCW72EcRv-wkpDkmsGQ,"[cafe, gym, general_contractor, health, school...",3.8,391.0,"Hornchurch Road, Hornchurch"
4,Eastbrook Cafe & Restuarant,"{'location': {'lat': 51.5508213, 'lng': 0.1614...",ChIJmSZw6z2l2EcRpS8prTdOqic,"[restaurant, meal_delivery, cafe, meal_takeawa...",4.3,91.0,"264 Rainham Road South, Dagenham"
...,...,...,...,...,...,...,...
655,The British Library,"{'location': {'lat': 51.52997169999999, 'lng':...",ChIJlRMXcDsbdkgRJdsP3nlUkBg,"[library, tourist_attraction, cafe, store, res...",4.5,2637.0,"96 Euston Road, London"
656,The Table Café,"{'location': {'lat': 51.5054844, 'lng': -0.099...",ChIJbc-9tKgEdkgR2qNGtGhKWLc,"[cafe, restaurant, food, point_of_interest, es...",4.3,1982.0,"83 Southwark Street, London"
657,Curzon Soho,"{'location': {'lat': 51.5127004, 'lng': -0.130...",ChIJR_tP9tIEdkgR50LK64QCsck,"[movie_theater, cafe, bar, restaurant, food, p...",4.5,1586.0,"99 Shaftesbury Avenue, London"
658,ODEON Surrey Quays,"{'location': {'lat': 51.4959322, 'lng': -0.044...",ChIJGTY0qN8CdkgR5fzIXjzgJsY,"[movie_theater, cafe, store, food, point_of_in...",3.9,2959.0,"Surrey Quays Leisure Park, Redriff Road, London"
659,Swan London,"{'location': {'lat': 51.5082418, 'lng': -0.096...",ChIJ70dbCqkEdkgR_2rXCHnP0aQ,"[restaurant, cafe, bar, food, point_of_interes...",4.3,3039.0,"21 New Globe Walk, Bankside, London"

## Data Cleaning

Total Number of Ratings in the column 'Number_Ratings' can only be interger

In [12]:
cafe_details['Number_Ratings'].fillna(0, inplace=True)
cafe_details['Number_Ratings'] = cafe_details['Number_Ratings'].astype(int)
cafe_details

,Cafe_Name,Cafe_Coordinates,Place_Id,Cafe_Types,Rating,Number_Ratings,Vicinity
0,Take a Break,"{'location': {'lat': 51.55102600000001, 'lng':...",ChIJP5iSZRul2EcRuLlMBSZy-JY,"[cafe, point_of_interest, food, establishment]",4.0,40,"244 Oxlow Lane, Dagenham"
1,Asda Dagenham Superstore,"{'location': {'lat': 51.5301912, 'lng': 0.1422...",ChIJdwGW-HOl2EcRkRKhL91oI_s,"[supermarket, atm, pharmacy, cafe, gas_station...",3.6,822,"Merrielands Crescent, Dagenham"
2,Becontree Heath Leisure Centre,"{'location': {'lat': 51.5609465, 'lng': 0.1488...",ChIJfRvpP_yk2EcRMHJ8P6PE448,"[gym, cafe, health, school, point_of_interest,...",3.6,824,"Althorne Way, Dagenham"
3,Harrow Lodge Leisure Centre,"{'location': {'lat': 51.5613365, 'lng': 0.2070...",ChIJbz00eCW72EcRv-wkpDkmsGQ,"[cafe, gym, general_contractor, health, school...",3.8,391,"Hornchurch Road, Hornchurch"
4,Eastbrook Cafe & Restuarant,"{'location': {'lat': 51.5508213, 'lng': 0.1614...",ChIJmSZw6z2l2EcRpS8prTdOqic,"[restaurant, meal_delivery, cafe, meal_takeawa...",4.3,91,"264 Rainham Road South, Dagenham"
...,...,...,...,...,...,...,...
655,The British Library,"{'location': {'lat': 51.52997169999999, 'lng':...",ChIJlRMXcDsbdkgRJdsP3nlUkBg,"[library, tourist_attraction, cafe, store, res...",4.5,2637,"96 Euston Road, London"
656,The Table Café,"{'location': {'lat': 51.5054844, 'lng': -0.099...",ChIJbc-9tKgEdkgR2qNGtGhKWLc,"[cafe, restaurant, food, point_of_interest, es...",4.3,1982,"83 Southwark Street, London"
657,Curzon Soho,"{'location': {'lat': 51.5127004, 'lng': -0.130...",ChIJR_tP9tIEdkgR50LK64QCsck,"[movie_theater, cafe, bar, restaurant, food, p...",4.5,1586,"99 Shaftesbury Avenue, London"
658,ODEON Surrey Quays,"{'location': {'lat': 51.4959322, 'lng': -0.044...",ChIJGTY0qN8CdkgR5fzIXjzgJsY,"[movie_theater, cafe, store, food, point_of_in...",3.9,2959,"Surrey Quays Leisure Park, Redriff Road, London"
659,Swan London,"{'location': {'lat': 51.5082418, 'lng': -0.096...",ChIJ70dbCqkEdkgR_2rXCHnP0aQ,"[restaurant, cafe, bar, food, point_of_interes...",4.3,3039,"21 New Globe Walk, Bankside, London"

Clean the 'Cafe_Coordinates' into "latitude, longtitude" form

In [15]:
tab = cafe_details['Cafe_Coordinates'][0]
tab

{'location': {'lat': 51.55102600000001, 'lng': 0.1547964},
 'viewport': {'northeast': {'lat': 51.5524568302915, 'lng': 0.156172280291502},
  'southwest': {'lat': 51.5497588697085, 'lng': 0.153474319708498}}}

In [17]:
def clean_coordinates(geometry):
    """
    This function is to clean the data of the 'Cafe_Coordinates' column to only keep the degree form and in the format of lat, long
    geometry: dict all detail locations in different form
    Return: str in the format of lat, long
    """
    # Extract latitude and longitude from the 'location' key
    lat = geometry['location']['lat']
    lng = geometry['location']['lng']
    return f"{lat}, {lng}"
cafe_details['Cafe_Coordinates'] = cafe_details['Cafe_Coordinates'].apply(clean_coordinates)
cafe_details

,Cafe_Name,Cafe_Coordinates,Place_Id,Cafe_Types,Rating,Number_Ratings,Vicinity
0,Take a Break,"51.55102600000001, 0.1547964",ChIJP5iSZRul2EcRuLlMBSZy-JY,"[cafe, point_of_interest, food, establishment]",4.0,40,"244 Oxlow Lane, Dagenham"
1,Asda Dagenham Superstore,"51.5301912, 0.1422174",ChIJdwGW-HOl2EcRkRKhL91oI_s,"[supermarket, atm, pharmacy, cafe, gas_station...",3.6,822,"Merrielands Crescent, Dagenham"
2,Becontree Heath Leisure Centre,"51.5609465, 0.1488995",ChIJfRvpP_yk2EcRMHJ8P6PE448,"[gym, cafe, health, school, point_of_interest,...",3.6,824,"Althorne Way, Dagenham"
3,Harrow Lodge Leisure Centre,"51.5613365, 0.207073",ChIJbz00eCW72EcRv-wkpDkmsGQ,"[cafe, gym, general_contractor, health, school...",3.8,391,"Hornchurch Road, Hornchurch"
4,Eastbrook Cafe & Restuarant,"51.5508213, 0.1614183",ChIJmSZw6z2l2EcRpS8prTdOqic,"[restaurant, meal_delivery, cafe, meal_takeawa...",4.3,91,"264 Rainham Road South, Dagenham"
...,...,...,...,...,...,...,...
655,The British Library,"51.52997169999999, -0.1276759",ChIJlRMXcDsbdkgRJdsP3nlUkBg,"[library, tourist_attraction, cafe, store, res...",4.5,2637,"96 Euston Road, London"
656,The Table Café,"51.5054844, -0.0998167",ChIJbc-9tKgEdkgR2qNGtGhKWLc,"[cafe, restaurant, food, point_of_interest, es...",4.3,1982,"83 Southwark Street, London"
657,Curzon Soho,"51.5127004, -0.1305849",ChIJR_tP9tIEdkgR50LK64QCsck,"[movie_theater, cafe, bar, restaurant, food, p...",4.5,1586,"99 Shaftesbury Avenue, London"
658,ODEON Surrey Quays,"51.4959322, -0.0447721",ChIJGTY0qN8CdkgR5fzIXjzgJsY,"[movie_theater, cafe, store, food, point_of_in...",3.9,2959,"Surrey Quays Leisure Park, Redriff Road, London"
659,Swan London,"51.5082418, -0.09652360000000001",ChIJ70dbCqkEdkgR_2rXCHnP0aQ,"[restaurant, cafe, bar, food, point_of_interes...",4.3,3039,"21 New Globe Walk, Bankside, London"

## Extract latitude and longtitude for Kinetica

In [19]:
# Create a new DataFrame with separate 'lat' and 'lng' columns from 'Cafe_Coordinates'
# Create a copy of the original dataframe
cafe_details_kinetica = cafe_details.copy()  

# Split the 'Cafe_Coordinates' column into 'lat' and 'lng'
cafe_details_kinetica[['lat', 'lng']] = cafe_details_kinetica['Cafe_Coordinates'].str.split(',', expand=True)

# Convert the 'lat' and 'lng' columns to numeric (float) data type
cafe_details_kinetica['lat'] = pd.to_numeric(cafe_details_kinetica['lat'])
cafe_details_kinetica['lng'] = pd.to_numeric(cafe_details_kinetica['lng'])

# Display the new DataFrame with 'lat' and 'lng' columns
cafe_details_kinetica

,Cafe_Name,Cafe_Coordinates,Place_Id,Cafe_Types,Rating,Number_Ratings,Vicinity,lat,lng
0,Take a Break,"51.55102600000001, 0.1547964",ChIJP5iSZRul2EcRuLlMBSZy-JY,"[cafe, point_of_interest, food, establishment]",4.0,40,"244 Oxlow Lane, Dagenham",51.551026,0.154796
1,Asda Dagenham Superstore,"51.5301912, 0.1422174",ChIJdwGW-HOl2EcRkRKhL91oI_s,"[supermarket, atm, pharmacy, cafe, gas_station...",3.6,822,"Merrielands Crescent, Dagenham",51.530191,0.142217
2,Becontree Heath Leisure Centre,"51.5609465, 0.1488995",ChIJfRvpP_yk2EcRMHJ8P6PE448,"[gym, cafe, health, school, point_of_interest,...",3.6,824,"Althorne Way, Dagenham",51.560947,0.148899
3,Harrow Lodge Leisure Centre,"51.5613365, 0.207073",ChIJbz00eCW72EcRv-wkpDkmsGQ,"[cafe, gym, general_contractor, health, school...",3.8,391,"Hornchurch Road, Hornchurch",51.561337,0.207073
4,Eastbrook Cafe & Restuarant,"51.5508213, 0.1614183",ChIJmSZw6z2l2EcRpS8prTdOqic,"[restaurant, meal_delivery, cafe, meal_takeawa...",4.3,91,"264 Rainham Road South, Dagenham",51.550821,0.161418
...,...,...,...,...,...,...,...,...,...
655,The British Library,"51.52997169999999, -0.1276759",ChIJlRMXcDsbdkgRJdsP3nlUkBg,"[library, tourist_attraction, cafe, store, res...",4.5,2637,"96 Euston Road, London",51.529972,-0.127676
656,The Table Café,"51.5054844, -0.0998167",ChIJbc-9tKgEdkgR2qNGtGhKWLc,"[cafe, restaurant, food, point_of_interest, es...",4.3,1982,"83 Southwark Street, London",51.505484,-0.099817
657,Curzon Soho,"51.5127004, -0.1305849",ChIJR_tP9tIEdkgR50LK64QCsck,"[movie_theater, cafe, bar, restaurant, food, p...",4.5,1586,"99 Shaftesbury Avenue, London",51.512700,-0.130585
658,ODEON Surrey Quays,"51.4959322, -0.0447721",ChIJGTY0qN8CdkgR5fzIXjzgJsY,"[movie_theater, cafe, store, food, point_of_in...",3.9,2959,"Surrey Quays Leisure Park, Redriff Road, London",51.495932,-0.044772
659,Swan London,"51.5082418, -0.09652360000000001",ChIJ70dbCqkEdkgR_2rXCHnP0aQ,"[restaurant, cafe, bar, food, point_of_interes...",4.3,3039,"21 New Globe Walk, Bankside, London",51.508242,-0.096524

## Get Review details

Trial Codes

In [21]:
for index, row in cafe_details.iterrows():
    place_id = row['Place_Id']
    cafe_name = row['Cafe_Name']
    # Extract the place id for the prefix of the review id
    prefix = place_id
    
    place_details_url = f"https://maps.googleapis.com/maps/api/place/details/json?place_id={place_id}&fields=reviews&key={api_key}"

    # Send the request and get the response
    response = requests.get(place_details_url)
    details = response.json()

    # Extract the reviews (ONLY TOP 5 ranked by relevance, that are most informative and helpful for users looking for insights)
    reviews = details['result'].get('reviews', [])
    review_counter = 1
    
    # Process each review
    for review in reviews:
        # Generate review_id
        review_id = f"{prefix}{review_counter}"
        
        # Retrieve author's name and when it is written
        author_name = review.get('author_name')
        relative_time_description = review.get('relative_time_description')
        review_counter += 1
        
        print(f"Review_ID: {review_id}, Author: {author_name}, Time: {relative_time_description}")
    print(f"{cafe_name}------------------------------------------------------------------")

Review_ID: ChIJP5iSZRul2EcRuLlMBSZy-JY1, Author: Terence j Cleary, Time: a month ago
Review_ID: ChIJP5iSZRul2EcRuLlMBSZy-JY2, Author: George Reeves, Time: a year ago
Review_ID: ChIJP5iSZRul2EcRuLlMBSZy-JY3, Author: Jack J, Time: a year ago
Review_ID: ChIJP5iSZRul2EcRuLlMBSZy-JY4, Author: Samina Barker, Time: a year ago
Review_ID: ChIJP5iSZRul2EcRuLlMBSZy-JY5, Author: Jaime Wiles, Time: 2 years ago
Take a Break------------------------------------------------------------------
Review_ID: ChIJdwGW-HOl2EcRkRKhL91oI_s1, Author: Salim Patel, Time: 7 months ago
Review_ID: ChIJdwGW-HOl2EcRkRKhL91oI_s2, Author: The Throwback Guy, Time: 4 months ago
Review_ID: ChIJdwGW-HOl2EcRkRKhL91oI_s3, Author: Jackie Cox, Time: a month ago
Review_ID: ChIJdwGW-HOl2EcRkRKhL91oI_s4, Author: Abid Ahmed, Time: a week ago
Review_ID: ChIJdwGW-HOl2EcRkRKhL91oI_s5, Author: Adrian Zimny, Time: 4 months ago
Asda Dagenham Superstore------------------------------------------------------------------
Review_ID: ChIJfRvpP_yk2EcRMHJ8P6PE4481, Author: Renan Luiz, Time: a month ago
Review_ID: ChIJfRvpP_yk2EcRMHJ8P6PE4482, Author: Z Grigaitiene, Time: 2 months ago
Review_ID: ChIJfRvpP_yk2EcRMHJ8P6PE4483, Author: Adrian Stefan Iancu, Time: 4 months ago
Review_ID: ChIJfRvpP_yk2EcRMHJ8P6PE4484, Author: S D, Time: 5 months ago
Review_ID: ChIJfRvpP_yk2EcRMHJ8P6PE4485, Author: hukum chawla, Time: a week ago
Becontree Heath Leisure Centre------------------------------------------------------------------
Review_ID: ChIJbz00eCW72EcRv-wkpDkmsGQ1, Author: Leanne Salmon, Time: 6 months ago
Review_ID: ChIJbz00eCW72EcRv-wkpDkmsGQ2, Author: chris pawlina, Time: a month ago
Review_ID: ChIJbz00eCW72EcRv-wkpDkmsGQ3, Author: Julian Harris, Time: a month ago
Review_ID: ChIJbz00eCW72EcRv-wkpDkmsGQ4, Author: Omar Miah, Time: 4 months ago
Review_ID: ChIJbz00eCW72EcRv-wkpDkmsGQ5, Author: Ike (Focusman217), Time: 3 months ago
Harrow Lodge Leisure Centre------------------------------------------------------------------
Review_ID: ChIJmSZw6z2l2EcRpS8prTdOqic1, Author: Raihanul Siddique, Time: a year ago
Review_ID: ChIJmSZw6z2l2EcRpS8prTdOqic2, Author: John Lewis, Time: a month ago
Review_ID: ChIJmSZw6z2l2EcRpS8prTdOqic3, Author: Kam Bains, Time: 7 months ago
Review_ID: ChIJmSZw6z2l2EcRpS8prTdOqic4, Author: Feel_ TheFire, Time: 8 months ago
Review_ID: ChIJmSZw6z2l2EcRpS8prTdOqic5, Author: J F, Time: 3 years ago
Eastbrook Cafe & Restuarant------------------------------------------------------------------
Review_ID: ChIJnSemhv6k2EcR9ybePKhA6Es1, Author: Mark Fairbrass, Time: 3 months ago
Review_ID: ChIJnSemhv6k2EcR9ybePKhA6Es2, Author: Jojotheragdollcat (Josephine and Anabelle), Time: 4 months ago
Review_ID: ChIJnSemhv6k2EcR9ybePKhA6Es3, Author: Jacqui, Time: 2 months ago
Review_ID: ChIJnSemhv6k2EcR9ybePKhA6Es4, Author: Kulwinder Singh, Time: a month ago
Review_ID: ChIJnSemhv6k2EcR9ybePKhA6Es5, Author: Franky, Time: 10 months ago
FIDDLERS CAFE------------------------------------------------------------------
Review_ID: ChIJw0exmLWk2EcRxHSOqVLdhDo1, Author: Wafaa nice clipe, Time: 2 years ago
Review_ID: ChIJw0exmLWk2EcRxHSOqVLdhDo2, Author: Ellie May, Time: 3 months ago
Review_ID: ChIJw0exmLWk2EcRxHSOqVLdhDo3, Author: charlotte evans, Time: 2 months ago
Review_ID: ChIJw0exmLWk2EcRxHSOqVLdhDo4, Author: Sana Asghar, Time: 5 months ago
Review_ID: ChIJw0exmLWk2EcRxHSOqVLdhDo5, Author: Sandra Howard, Time: 5 months ago
bb's coffee & muffins------------------------------------------------------------------
Review_ID: ChIJmxBxcL2k2EcRBPbuxzhEjbs1, Author: James Holland, Time: a month ago
Review_ID: ChIJmxBxcL2k2EcRBPbuxzhEjbs2, Author: Smart_maintenance S, Time: 3 weeks ago
Review_ID: ChIJmxBxcL2k2EcRBPbuxzhEjbs3, Author: Christopher Witt, Time: 3 years ago
Review_ID: ChIJmxBxcL2k2EcRBPbuxzhEjbs4, Author: John Oxley, Time: 6 months ago
Review_ID: ChIJmxBxcL2k2EcRBPbuxzhEjbs5, Author: Janice Darrington, Time: a year ago
The Park Cafe------------------------------------------------------------------
Review_ID: ChIJI_k0xwGl2EcRAuS_d1XUIm41, Author: Nabeel Akram, Time: 2 months ago
Review_ID: ChIJI_k0xwGl2EcRAuS_d1XUIm42, Author: NYASHA Aideloje, Time: 3 months ago
Review_ID: ChIJI_k0xwGl2EcRAuS_d1XUIm43, Author: Beata Banytė, Time: 3 months ago
Review_ID: ChIJI_k0xwGl2EcRAuS_d1XUIm44, Author: mostaquim islam, Time: 3 months ago
Review_ID: ChIJI_k0xwGl2EcRAuS_d1XUIm45, Author: Nicolae-Ovidiu Musat, Time: 6 months ago
Shell------------------------------------------------------------------
Review_ID: ChIJHcUMy_2k2EcRi08StUy8GOQ1, Author: Aileen, Time: a month ago
Review_ID: ChIJHcUMy_2k2EcRi08StUy8GOQ2, Author: Mavin K, Time: 2 years ago
Review_ID: ChIJHcUMy_2k2EcRi08StUy8GOQ3, Author: Kyle Sewell, Time: 3 years ago
Review_ID: ChIJHcUMy_2k2EcRi08StUy8GOQ4, Author: Rita Santos, Time: 7 months ago
Review_ID: ChIJHcUMy_2k2EcRi08StUy8GOQ5, Author: Amir Raheem, Time: 3 years ago
Morrisons Cafe------------------------------------------------------------------
Review_ID: ChIJJ9Aiktqk2EcRkkktIFPy7Ng1, Author: Ed Calvert, Time: 5 months ago
Review_ID: ChIJJ9Aiktqk2EcRkkktIFPy7Ng2, Author: Mihai Chitu, Time: 10 months ago
Review_ID: ChIJJ9Aiktqk2EcRkkktIFPy7Ng3, Author: walumweya waluka, Time: a year ago
Review_ID: ChIJJ9Aiktqk2EcRkkktIFPy7Ng4, Author: Jade G, Time: 7 years ago
Review_ID: ChIJJ9Aiktqk2EcRkkktIFPy7Ng5, Author: Day “RealityKiller87”, Time: 4 years ago
bp------------------------------------------------------------------
Review_ID: ChIJVaUoVD2l2EcR5i7ZiZxIamI1, Author: Riz K, Time: 10 months ago
Review_ID: ChIJVaUoVD2l2EcR5i7ZiZxIamI2, Author: Marta K, Time: 3 months ago
Review_ID: ChIJVaUoVD2l2EcR5i7ZiZxIamI3, Author: Caz B., Time: a month ago
Review_ID: ChIJVaUoVD2l2EcR5i7ZiZxIamI4, Author: Karuxinha D.S, Time: 3 months ago
Review_ID: ChIJVaUoVD2l2EcR5i7ZiZxIamI5, Author: ridan rigardo, Time: 3 months ago
Costa Coffee------------------------------------------------------------------
Review_ID: ChIJDbURO8yk2EcRXuerEHrAuxw1, Author: Daniela Pletea, Time: 2 months ago
Review_ID: ChIJDbURO8yk2EcRXuerEHrAuxw2, Author: Tom Tall, Time: 5 months ago
Review_ID: ChIJDbURO8yk2EcRXuerEHrAuxw3, Author: John Oxley, Time: 6 months ago
Review_ID: ChIJDbURO8yk2EcRXuerEHrAuxw4, Author: Stonemason Landscapes, Time: 5 months ago
Review_ID: ChIJDbURO8yk2EcRXuerEHrAuxw5, Author: JT Ike, Time: 5 months ago
Mel's Cafe------------------------------------------------------------------
Review_ID: ChIJ5zHF98ik2EcRIHy8nGLOzRc1, Author: Amie Ferdinand, Time: 5 months ago
Review_ID: ChIJ5zHF98ik2EcRIHy8nGLOzRc2, Author: Aanam Asim, Time: 3 months ago
Review_ID: ChIJ5zHF98ik2EcRIHy8nGLOzRc3, Author: Narcis Herman, Time: 3 months ago
Review_ID: ChIJ5zHF98ik2EcRIHy8nGLOzRc4, Author: Jack and Rav, Time: a year ago
Review_ID: ChIJ5zHF98ik2EcRIHy8nGLOzRc5, Author: Umer Khaliq, Time: 8 months ago
Patisserie Valerie - Romford------------------------------------------------------------------
Review_ID: ChIJ3ZZSM8ik2EcRb_mKxIpJ1Gc1, Author: Steven Bunner, Time: 9 months ago
Review_ID: ChIJ3ZZSM8ik2EcRb_mKxIpJ1Gc2, Author: Shaimaa Elsarafy, Time: 3 months ago
Review_ID: ChIJ3ZZSM8ik2EcRb_mKxIpJ1Gc3, Author: T j s, Time: 3 months ago
Review_ID: ChIJ3ZZSM8ik2EcRb_mKxIpJ1Gc4, Author: Eileen Collier, Time: 5 months ago
Review_ID: ChIJ3ZZSM8ik2EcRb_mKxIpJ1Gc5, Author: Nicky Tann, Time: 6 months ago
Costa Coffee------------------------------------------------------------------
Review_ID: ChIJ6d55Nbak2EcRHzo7VFfrkmI1, Author: Adam Harris - Batt, Time: a month ago
Review_ID: ChIJ6d55Nbak2EcRHzo7VFfrkmI2, Author: Tasharn Sanganoo, Time: a year ago
Review_ID: ChIJ6d55Nbak2EcRHzo7VFfrkmI3, Author: Tom King, Time: a year ago
Review_ID: ChIJ6d55Nbak2EcRHzo7VFfrkmI4, Author: Michael, Time: 2 months ago
Review_ID: ChIJ6d55Nbak2EcRHzo7VFfrkmI5, Author: khushnud kabir, Time: 7 months ago
Cafe Chateau------------------------------------------------------------------
Review_ID: ChIJWZiKoumk2EcR6oiARs03Iis1, Author: Jennifer - Zeynab Hossain, Time: a month ago
Review_ID: ChIJWZiKoumk2EcR6oiARs03Iis2, Author: Jericho, Time: 5 months ago
Review_ID: ChIJWZiKoumk2EcR6oiARs03Iis3, Author: Sue-Ann Goodey, Time: 2 months ago
Review_ID: ChIJWZiKoumk2EcR6oiARs03Iis4, Author: Kamil Borkowski, Time: 2 months ago
Review_ID: ChIJWZiKoumk2EcR6oiARs03Iis5, Author: julka smaga, Time: 4 months ago
Café Shot------------------------------------------------------------------
Review_ID: ChIJ95BU_kek2EcRjE6XVfHFYXw1, Author: Supremo Fortis, Time: 4 months ago
Review_ID: ChIJ95BU_kek2EcRjE6XVfHFYXw2, Author: Deejie 007, Time: a year ago
Review_ID: ChIJ95BU_kek2EcRjE6XVfHFYXw3, Author: Javina Chana, Time: 2 months ago
Review_ID: ChIJ95BU_kek2EcRjE6XVfHFYXw4, Author: Mr. T, Time: a month ago
Review_ID: ChIJ95BU_kek2EcRjE6XVfHFYXw5, Author: Safiyyah xxx, Time: 7 months ago
Costa Coffee------------------------------------------------------------------
Review_ID: ChIJ9cyXebak2EcRJeRja8SMOa01, Author: Prodigal Fur, Time: a month ago
Review_ID: ChIJ9cyXebak2EcRJeRja8SMOa02, Author: Charlotte Higginson, Time: a year ago
Review_ID: ChIJ9cyXebak2EcRJeRja8SMOa03, Author: Kamran Araf, Time: 2 months ago
Review_ID: ChIJ9cyXebak2EcRJeRja8SMOa04, Author: Tony Clay, Time: 9 months ago
Review_ID: ChIJ9cyXebak2EcRJeRja8SMOa05, Author: ItsYourGirlBrogan X, Time: 3 months ago
Tea Pot Cafe Romford------------------------------------------------------------------

Review_ID: ChIJc_JIoLWk2EcR58mbBv-WHrM1, Author: TooManyFandoms !, Time: 2 months ago
Review_ID: ChIJc_JIoLWk2EcR58mbBv-WHrM2, Author: Lesley Mussard, Time: 10 months ago
Review_ID: ChIJc_JIoLWk2EcR58mbBv-WHrM3, Author: Georgia, Time: 9 months ago
Review_ID: ChIJc_JIoLWk2EcR58mbBv-WHrM4, Author: That Geezer, Time: a year ago
Review_ID: ChIJc_JIoLWk2EcR58mbBv-WHrM5, Author: Jennifer - Zeynab Hossain, Time: 2 weeks ago
Caffe Della Continental------------------------------------------------------------------
Review_ID: ChIJTYFDde8ZdkgR9KCXadpVz181, Author: Tj X, Time: 2 months ago
Review_ID: ChIJTYFDde8ZdkgR9KCXadpVz182, Author: Seun Samuel, Time: a year ago
Review_ID: ChIJTYFDde8ZdkgR9KCXadpVz183, Author: Adrian Adamczyk, Time: 3 weeks ago
Review_ID: ChIJTYFDde8ZdkgR9KCXadpVz184, Author: Ümit Durdu, Time: a year ago
Review_ID: ChIJTYFDde8ZdkgR9KCXadpVz185, Author: فاطمه, Time: 8 months ago
bp------------------------------------------------------------------
Review_ID: ChIJB_gqY-8ZdkgRU6aKu6Fdqfk1, Author: Niki Ashra, Time: a month ago
Review_ID: ChIJB_gqY-8ZdkgRU6aKu6Fdqfk2, Author: Leslie Perry, Time: a week ago
Review_ID: ChIJB_gqY-8ZdkgRU6aKu6Fdqfk3, Author: Gina Bull, Time: 3 weeks ago
Review_ID: ChIJB_gqY-8ZdkgRU6aKu6Fdqfk4, Author: Sara Escalona-Rodriguez, Time: a month ago
Review_ID: ChIJB_gqY-8ZdkgRU6aKu6Fdqfk5, Author: Sivakumar Venugopal, Time: a year ago
artsdepot------------------------------------------------------------------
Review_ID: ChIJ_els_lMZdkgRSSLrKRSAxxY1, Author: Adam Pelling, Time: a year ago
Review_ID: ChIJ_els_lMZdkgRSSLrKRSAxxY2, Author: Simon Vessey, Time: a month ago
Review_ID: ChIJ_els_lMZdkgRSSLrKRSAxxY3, Author: anne adbar, Time: 6 months ago
Review_ID: ChIJ_els_lMZdkgRSSLrKRSAxxY4, Author: EVANS BOAHENG, Time: 6 months ago
Review_ID: ChIJ_els_lMZdkgRSSLrKRSAxxY5, Author: Mataku Solo, Time: a month ago
New River Sport, Tennis & Fitness------------------------------------------------------------------
Review_ID: ChIJe8io5ywadkgRuYAsxazLI881, Author: Zuzi, Time: 5 months ago
Review_ID: ChIJe8io5ywadkgRuYAsxazLI882, Author: Joanne Lucas-Stone, Time: 2 weeks ago
Review_ID: ChIJe8io5ywadkgRuYAsxazLI883, Author: Malka Nagel, Time: a year ago
Review_ID: ChIJe8io5ywadkgRuYAsxazLI884, Author: R Anis, Time: 3 months ago
Review_ID: ChIJe8io5ywadkgRuYAsxazLI885, Author: Griff Hayward, Time: 8 months ago
Sable D'Or------------------------------------------------------------------

KeyboardInterrupt: